from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(343, 377)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setBold(True)
        login.setFont(font)
        icon = QtGui.QIcon.fromTheme("emblem-system")
        login.setWindowIcon(icon)
        login.setStyleSheet("")
        self.button_login = QtWidgets.QPushButton(parent=login)
        self.button_login.setGeometry(QtCore.QRect(40, 290, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(16)
        font.setBold(True)
        self.button_login.setFont(font)
        self.button_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_login.setStyleSheet("border-radius: 10px;\n"
"background-color: #004655;\n"
"color: #eee;")
        self.button_login.setObjectName("button_login")
        self.username = QtWidgets.QLineEdit(parent=login)
        self.username.setGeometry(QtCore.QRect(90, 150, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.username.setFont(font)
        self.username.setStyleSheet("border-radius: 10px;\n"
"color: #eee;\n"
"background-color: #749993;")
        self.username.setObjectName("username")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=login)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 150, 71, 51))
        self.lineEdit_2.setStyleSheet("border-radius: 10px;\n"
"background-color: #749993;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=login)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 210, 71, 51))
        self.lineEdit_3.setStyleSheet("border-radius: 10px;\n"
"background-color: #749993;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.password = QtWidgets.QLineEdit(parent=login)
        self.password.setGeometry(QtCore.QRect(90, 210, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.password.setFont(font)
        self.password.setStyleSheet("border-radius: 10px;\n"
"color: #eee;\n"
"background-color: #749993;")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.logo_padlock = QtWidgets.QLabel(parent=login)
        self.logo_padlock.setGeometry(QtCore.QRect(50, 220, 31, 31))
        self.logo_padlock.setAutoFillBackground(False)
        self.logo_padlock.setText("")
        self.logo_padlock.setPixmap(QtGui.QPixmap("unprotected.png"))
        self.logo_padlock.setScaledContents(True)
        self.logo_padlock.setObjectName("logo_padlock")
        self.logo_user = QtWidgets.QLabel(parent=login)
        self.logo_user.setGeometry(QtCore.QRect(50, 160, 31, 31))
        self.logo_user.setText("")
        self.logo_user.setPixmap(QtGui.QPixmap("user.png"))
        self.logo_user.setScaledContents(True)
        self.logo_user.setObjectName("logo_user")
        self.logo_wilmar = QtWidgets.QLabel(parent=login)
        self.logo_wilmar.setGeometry(QtCore.QRect(70, 40, 221, 61))
        self.logo_wilmar.setText("")
        self.logo_wilmar.setPixmap(QtGui.QPixmap("F34.SI_BIG.png"))
        self.logo_wilmar.setScaledContents(True)
        self.logo_wilmar.setObjectName("logo_wilmar")
        self.lineEdit_2.raise_()
        self.button_login.raise_()
        self.username.raise_()
        self.lineEdit_3.raise_()
        self.password.raise_()
        self.logo_padlock.raise_()
        self.logo_user.raise_()
        self.logo_wilmar.raise_()

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)
        login.setTabOrder(self.username, self.password)
        login.setTabOrder(self.password, self.button_login)
        login.setTabOrder(self.button_login, self.lineEdit_3)
        login.setTabOrder(self.lineEdit_3, self.lineEdit_2)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Login System"))
        self.button_login.setText(_translate("login", "login"))
        self.username.setPlaceholderText(_translate("login", "username...."))
        self.password.setPlaceholderText(_translate("login", "password...."))
